sudo: false
language: node_js
cache:
  yarn: true
  directories:
  - "~/.npm"
node_js: '8'
python: "3.5"
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - yarn install
script: yarn build
branches:
  only: master
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: ibchamilton
  skip_cleanup: true
  local_dir: public
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
