title = "Immanuel Baptist Church"
baseURL = "/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-98114991-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/IBCHamilton"
  twitter = ""
  instagram = ""
  youtube = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/ChurchEntrance_Compressed.jpg"


[[menu.main]]
  name = "About"
  url = "/about/"
  weight = "1"

[[menu.main]]
  name = "Ministries"
  url = "/ministries/"
  weight = "5"

[[menu.main]]
  name = "Missions"
  url = "/missions/"
  weight = "10"

[[menu.main]]
  name = "Sermons"
  url = "/sermons/"
  weight = "10"

[[menu.main]]
  name = "Events"
  url = "/events/"
  weight = "15"

[[menu.main]]
  name = "Links"
  url = "/links/"
  weight = "20"

