backend:
  name: github
  repo: green-arrow/ibchamilton
  branch: master
  site_domain: ibchamilton.netlify.com

# Physical location of uploads in folder structure
media_folder: "static/images/uploads"
# HTML 'src' location
public_folder: "/images/uploads"

collections:
  - name: "about"
    label: "About Us Page"
    folder: "site/content/about"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      #- {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "ministries"
    label: "Ministries Page"
    folder: "site/content/ministries"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      #- {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "missions"
    label: "Missions Page"
    folder: "site/content/missions"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      #- {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "sermon"
    label: "Sermon"
    folder: "site/content/sermons"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Sermon Title", name: "title", widget: "string"}
      - {label: "Sermon Date", name: "date", widget: "datetime"}
      - {label: "Youtube Video ID", name: "youtube_id", widget: "string"}
      - {label: "Sermon Description", name: "body", widget: "markdown"}